function getParentLoop(a){if($("#"+a)){var b=$("#"+a).attr("class");if(b!=null&&b!="undefined"&&b.length>0&&b.indexOf("child-of-")!=-1&&(b=b.split(" "),b!=null&&b.length>0)){for(var g="",f=0;f<b.length;f++)if(b[f].indexOf("child-of-")!=-1){g=b[f].split("child-of-")[1];break}if(g.length>0)return getParentLoop(g)+" "+a}}return a}var treePerspectiveArray=[],treeKPIArray=[],myValuesArray=[{id:"",myValues:[],trendChartValues:[],colors:[]}];
$.fn.toggleBranch=function(){if($(this).hasClass("collapsed")){var a=$(this).attr("id");$(this).attr("class");a.split("_node_");a.split("_node_");$(this).expand();for(a=0;a<myValuesArray.length;a++)$("#sparklines"+myValuesArray[a].id).html(""),$("#trendLine"+myValuesArray[a].id).html(""),$("#sparklines"+myValuesArray[a].id).sparkline(myValuesArray[a].myValues,{type:"bullet",performanceColor:"blue",targetColor:"blue",width:"auto",height:"auto",targetWidth:3,rangeColors:myValuesArray[a].colors}),$("#trendLine"+
myValuesArray[a].id).sparkline(myValuesArray[a].trendChartValues,{barColor:"red"})}else $(this).hasClass("expanded")&&$(this).removeClass("expanded").collapse();return this};function loadmetergraph(a,b){document.getElementById(b).src=a}
function showKPIDetail(a,b){BalanceScorecardAjax.getKPIDetail({kpiKey:a,dateKey:b},{callback:function(a){if(a!=null)a=' <table width="700" height="300" border="0" align="center" style="text-decoration:none; background-color:\t#e6e6fa" class="popup">  <tr>     <td width="140" colspan="1" class="tdpopup">KPI Name </td><td>'+a.kpiName+"</td>  </tr>   <tr>  \t<td>Objective </td> <td>"+a.objective+"</td>  </tr>  <tr>  \t<td>Formula</td><td>"+a.formulaDesc+"</td>  </tr>  <tr>     <td>Definition </td><td>"+
a.kpiDesc+"</td>  </tr>  <tr>     <td>Unit of measure</td><td>"+a.uom+"</td>  </tr>  <tr>  \t<td>Source of information <br>/ Data collector</td><td>"+a.dataSource+"</td>  </tr>   <tr>  \t<td>Target range</td><td>"+a.targetRangeDesc+"</td>  </tr>  <tr>  \t<td>  Last revise</td><td>"+a.lastRevisedDT+"</td>  </tr>  </table>",$("#bscKPIDetail").html(a),$.facebox.settings.closeImage=_path+"/chartLib/images/closelabel.png",jQuery.facebox({div:"#bscKPIDetail"})}})}
function showKPIBarChart(a,b,g,f){var c=$('select[id="bscOwner"]').val(),k=$('select[id="bscYear"]').val(),d=$('select[id="bscMonth"]').val();loadmetergraph("mixChart.jsp?bscOwner="+c+"&bscYear="+k+"&bscMonth="+d+"&perspectiveKey="+a+"&kpiKey="+b+"&dateKey="+g+"&accumulatedFlag="+f,"ifrmgr_"+a)}
function listYear(){var a="";BalanceScorecardAjax.listYear({callback:function(b){a+='<select name="bscYear" id="bscYear" onchange="listOwnerResult()">';a+='<option value="0">-- Select Year --</option>';if(b!=null&&b.length>0)for(var g=0;g<b.length;g++)a=a+'<option value="'+b[g]+'">'+b[g]+"</option>";a+="</select>";$("#bscYearElement").html(a)}})}function clearTargetElement(){$(".targetAllElement").html("");clearAllPerspectiveArray()}
function clearAllPerspectiveArray(){for(var a=0;a<treePerspectiveArray.length;a++)$("#row_perspective_"+treePerspectiveArray[a]).css("display","none")}
function listOwnerResult(){var a=$('select[id="bscYear"]').val(),b=$('select[id="bscMonth"]').val();clearTargetElement();var g="";BalanceScorecardAjax.listOwnerResult(a,b,{callback:function(a){g+='<select name="bscOwner" id="bscOwner" onchange="clearTargetElement()">';g+='<option value="0">-- Select Owner --</option>';if(a!=null&&a.length>0)for(var c=0;c<a.length;c++)g=g+'<option value="'+a[c].kpiOwnerKey+'">'+a[c].kpiOwnerName+"</option>";g+="</select>";$("#bscOwnerElement").html(g)}})}
function returnTogaugeMeter(a){var b=$('select[id="bscOwner"]').val(),g=$('select[id="bscYear"]').val(),f=$('select[id="bscMonth"]').val();BalanceScorecardAjax.getKPIListAndChartLevel0(g,f,b,a,{callback:function(c){for(var b=0;b<c.length;b++){var d=c[b].kpiresultthresholdDTOs;d!=null&&d.length>0&&($().number_format(d[0].kpiOwnerWeighting,{precision:0,decimalSeparator:"."}),$().number_format(d[0].perspectiveWeighting,{precision:0,decimalSeparator:"."}),d[0].updatedDT!=null&&$.format.date(d[0].updatedDT,
"dd/MM/yyyy"));for(var h=0;h<d.length;h++)$().number_format(d[h].endThreshold,{precision:0,decimalSeparator:"."}),d[h].id.colorCode=="red"?($().number_format(d[h].endThreshold,{precision:0,decimalSeparator:"."}),$().number_format(d[h].beginThreshold,{precision:0,decimalSeparator:"."})):d[h].id.colorCode=="yellow"?($().number_format(d[h].endThreshold,{precision:0,decimalSeparator:"."}),$().number_format(d[h].beginThreshold,{precision:0,decimalSeparator:"."})):d[h].id.colorCode=="green"&&($().number_format(d[h].endThreshold,
{precision:0,decimalSeparator:"."}),$().number_format(d[h].beginThreshold,{precision:0,decimalSeparator:"."})),percentActualVsTargettargetValue=d[h].percentActualVsTarget}loadmetergraph("meterChart.jsp?gvalue="+percentActualVsTargettargetValue,"ifrmgr_"+a)}})}
function viewKPI(){var a=$('select[id="bscOwner"]').val(),b=$('select[id="bscYear"]').val(),g=$('select[id="bscMonth"]').val();BalanceScorecardAjax.getKPIOverall(b,g,a,{callback:function(c){var k,d,h=[],p=[],e=0;if(c!=null&&c.length==3){for(var j=0;j<c.length;j++)h[j]=c[j].colorCode,p[j]=$().number_format(c[j].endThreshold,{precision:0,decimalSeparator:"."}),c[j].colorCode=="red"?$().number_format(c[j].endThreshold,{precision:0,decimalSeparator:"."}):c[j].colorCode=="yellow"?$().number_format(c[j].endThreshold,
{precision:0,decimalSeparator:"."}):c[j].colorCode=="green"&&$().number_format(c[j].endThreshold,{precision:0,decimalSeparator:"."}),e=$().number_format(c[j].percentActualVsTarget,{precision:0,decimalSeparator:"."}),k=c[j].actualValue,d=c[j].targetValue;c=[d,k,p[2],p[1],p[0]];$(".targetAllElement").sparkline(c,{type:"bullet",performanceColor:"blue",targetColor:"blue",width:"auto",height:"auto",targetWidth:3,rangeColors:[h[2],h[1],h[0]]});h=document.getElementById("targetAllSparkline");h.title=e+"%";
h.href=_path+"/SNPDashBoard/PopupBullet.jsp?bscOwner="+a+"&bscYear="+b+"&bscMonth="+g}}});var f='<table width="100%"    border="0">';BalanceScorecardAjax.getPerspective(a,b,g,{callback:function(a){treePerspectiveArray=[];for(var b=0;b<a.length;b++){var d="tdbscNameFin";b%2==0&&(d="tdbscNameCus");f=f+'<tr>\t<td colspan="1"  class="'+d+'" align="left">\t\t<div onclick="showhidebsc(\''+a[b].perspectiveKey+'\')" style="cursor: pointer;" class="bsc">'+a[b].perspectiveName+'</div>\t</td>\t<td   class="'+
d+'" align="center" width="450">\t\t<a style="cursor: pointer;" onclick="returnTogaugeMeter(\''+a[b].perspectiveKey+'\')" class="bsc"> Return to Gauge Meter</a>\t</td></tr><tr valign="top" id="row_perspective_'+a[b].perspectiveKey+'" style="display: none;">\t<td align="top"   align="left"><div id="tree_perspective_'+a[b].perspectiveKey+'" style="height:350px;overflow:auto;"></div>\t</td>\t<td  align="center" width="450"><div id="gaugeDiv_'+a[b].perspectiveKey+'" style="width: 50; height: 50"><iframe  id = "ifrmgr_'+
a[b].perspectiveKey+'"width=450 height=350 src=""marginwidth="0" marginheight="0" vspace="0" hspace="0" frameborder="0" align="middle" scrolling="no"></iframe></div>\t</td></tr>';treePerspectiveArray.push(a[b].perspectiveKey)}f+="</table>";$("#perspectiveElement").html(f)}})}var detailKPI_ID_Array=[];
function showhidebsc(a){var b=document.getElementById("row_perspective_"+a),g=$("#tree_perspective_"+a);if(b.style.display=="none"){var f=$('select[id="bscOwner"]').val(),c=$('select[id="bscYear"]').val(),k=$('select[id="bscMonth"]').val();b.style.display="";var d='<table  width="100%" height="20" class="bscTreegrid_'+a+'" border="0"><thead>\t<tr height="5" align="center">\t\t<td width="43%" class="tdsubheader">KPI</td>\t\t<td width="20px" class="tdsubheader"></td>\t\t\t<td width="6%" class="tdsubheader">KPI Weight</td>\t\t<td width="6%" class="tdsubheader">P. Weight</td>\t\t<td width="4%" class="tdsubheader">Freq</td>\t\t\t<td width="7%" class="tdsubheader">Target</td> \t\t<td width="7%" class="tdsubheader">Actual</td>\t\t\t<td width="10%" class="tdsubheader">Target</td>\t\t\t<td width="10%" class="tdsubheader">Trend</td>\t\t<td width="12%"\tclass="tdsubheader" >Last Updated</td>\t</tr></thead><tbody>';
BalanceScorecardAjax.getKPIListAndChartRecursive(c,k,f,a,{callback:function(b){for(var c=0;c<b.length;c++){var e=b[c].kpiresultthresholdDTOs,j=b[c].childOf!=null?'class="child-of-'+a+"_node_"+b[c].childOf+'"':"",f=b[c].trendChart,k=0,q="",r,s,t,u;if(e!=null&&e.length>0)k=$().number_format(e[0].kpiOwnerWeighting,{precision:0,decimalSeparator:"."}),q=$().number_format(e[0].perspectiveWeighting,{precision:0,decimalSeparator:"."}),r=e[0].frequency,s=e[0].targetValue,t=e[0].actualValue,u=e[0].updatedDT!=
null?$.format.date(e[0].updatedDT,"dd/MM/yyyy"):"";for(var n,v,l="",w,x,o=[],m=[],y=[],i=0;i<e.length;i++)o[i]=e[i].id.colorCode,m[i]=$().number_format(e[i].endThreshold,{precision:0,decimalSeparator:"."}),e[i].id.colorCode=="red"?(n=$().number_format(e[i].endThreshold,{precision:0,decimalSeparator:"."}),$().number_format(e[i].beginThreshold,{precision:0,decimalSeparator:"."}),l=l+","+n):e[i].id.colorCode=="yellow"?(n=$().number_format(e[i].endThreshold,{precision:0,decimalSeparator:"."}),$().number_format(e[i].beginThreshold,
{precision:0,decimalSeparator:"."}),l=","+n+l):e[i].id.colorCode=="green"&&(n=$().number_format(e[i].endThreshold,{precision:0,decimalSeparator:"."}),$().number_format(e[i].beginThreshold,{precision:0,decimalSeparator:"."}),l=","+n+l),n=e[i].actualValue,v=e[i].targetValue,percentActualVsTargettargetValue=e[i].percentActualVsTarget,w=e[i].id.kpiKey,x=e[i].accumulatedFlag;l=v+","+n+","+m[2]+","+m[1]+","+m[0];e=o.length;for(m=0;m<e;m++)y[m]=o[e-1-m];o="_"+a+"_"+b[c].kpiKey;f=""+f.jan+","+f.feb+","+f.mar+
","+f.apr+","+f.may+","+f.jun+","+f.jul+","+f.aug+","+f.sep+","+f.oct+","+f.nov+","+f.dec+"";d=d+'<tr  height="5" id="'+a+"_node_"+b[c].kpiKey+'" '+j+'><td width="43%" style="padding-left: 20px;" ><a style="cursor: pointer;" onclick="showKPIBarChart(\''+a+"','"+b[c].kpiKey+"','"+b[c].dateKey+"','"+x+"')\">"+b[c].kpiName+'</a></td><td width="20px"  align="right"><a style="cursor: pointer;" id="KPIDetail_'+w+'" rel="facebox" class="KPIDetail" onclick="showKPIDetail(\''+b[c].kpiKey+"','"+b[c].dateKey+
'\')"><img src="'+_path+'/chartLib/images/question_shield.ico" width="20px" BORDER ="0"/></a>\t</td><td width="6%"  align="center">'+k+'%</td><td width="6%"  align="center">'+q+'%</td>\t\t\t<td width="4%" align="center">'+r+'</td><td width="7%"  align="center">'+s+'</td>\t\t<td width="7%" align="center">'+t+'</td><td width="7%"  align="center"><div   id="sparklines'+o+'" title="'+percentActualVsTargettargetValue+'%">'+l+'</div></td><td width="7%"  align="center"><div id="trendLine'+o+'" LineColor="red" >'+
f+'</div></td><td width="12%" align="center">'+u+"</td></tr>";myValuesArray[c]={id:o,myValues:l.split(","),trendChartValues:f.split(","),colors:y}}d+="</tbody></table>";g.html(d);for(c=0;c<myValuesArray.length;c++)$("#sparklines"+myValuesArray[c].id).sparkline(myValuesArray[c].myValues,{type:"bullet",performanceColor:"blue",targetColor:"blue",width:"auto",height:"auto",targetWidth:3,rangeColors:myValuesArray[c].colors}),$("#trendLine"+myValuesArray[c].id).sparkline(myValuesArray[c].trendChartValues,
{barColor:"red"});$(".bscTreegrid_"+a).treeTable();loadmetergraph("meterChart.jsp?gvalue="+percentActualVsTargettargetValue,"ifrmgr_"+a)}})}else b.style.display="none",g.html("")};